In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print("Numpy Version:", np.__version__)
print("Pandas Version:", pd.__version__)
print("Setup complete.")

Numpy Version: 2.4.3
Pandas Version: 3.0.1
Setup complete.


In [7]:
a = np.array([1,2,3,4])
print("Array:", a)
print("Shape:", a.shape)
print("Type:", a.dtype)

print("X2:", a*2)
print("Square:", a**2)
print("Sum:", a.sum())
print("Mean:", a.mean())

Array: [1 2 3 4]
Shape: (4,)
Type: int64
X2: [2 4 6 8]
Square: [ 1  4  9 16]
Sum: 10
Mean: 2.5


In [8]:
m = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
print("Matrix:\n", m)
print("Shape:", m.shape)
print("Row [0]:", m[0])
print("Element [1][2]:", m[1][2])

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Row [0]: [1 2 3]
Element [1][2]: 6


In [9]:
a = np.array([1,2,3])
b = np.array([4,5,6])

dot = np.dot(a,b)
print("Dot product:", dot)

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

C = np.dot(A,B)

print("Matrix multiplication", C)

Dot product: 32
Matrix multiplication [[19 22]
 [43 50]]


In [11]:
a = np.array([1,2,3,4,5,6])
print("Original array:", a)

b = a.reshape(2,3)
print("Reshaaped:", b)
print("New shape:", b.shape)

c = b.reshape(-1)
print("Flattened:", c)
print("Shape:", c.shape)

d = a.reshape(-1,1)
print("Column Vector", d)
print("Shape:", d.shape)

Original array: [1 2 3 4 5 6]
Reshaaped: [[1 2 3]
 [4 5 6]]
New shape: (2, 3)
Flattened: [1 2 3 4 5 6]
Shape: (6,)
Column Vector [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
Shape: (6, 1)


In [13]:
m = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

print("Shape:", m.shape)

print("First row:", m[0,:])
print("First Col:", m[:,0])
print("Last row:", m[-1,:])
print("Submatrix:\n", m[0:2,1:3])
print("Sample:",m[1:,2:])

Shape: (3, 4)
First row: [1 2 3 4]
First Col: [1 5 9]
Last row: [ 9 10 11 12]
Submatrix:
 [[2 3]
 [6 7]]
Sample: [[ 7  8]
 [11 12]]
